
#コアゲームプレイに関する全ての設定項目
[gameplay]
	#初期市民の数 [初期値: 4, 最低: 1, 最大: 10]
	#Range: 1 ~ 10
	initialcitizenamount = 4
	#建設中の建物の周りに建設用テープを設置する？ [初期値: true]
	builderplaceconstructiontape = true
	#プレイヤーに、無限に支給キャンプ/船を設置可能にする？ [初期値: false]
	allowinfinitesupplychests = false
	#プレイヤーがコロニーを放棄し、新たなコロニーを簡単に作れるようにする？注: これはバグだらけです。 [初期値: false]
	allowinfinitecolonies = false
	#他のディメンションのコロニーを許可する？ [初期値: true]
	allowotherdimcolonies = true
	#コロニーの初期の市民数を下回っている場合、新しい市民が産まれてくるまでの時間を変更します。 [初期値: 60, 最低: 10, 最大: 600]
	#Range: 10 ~ 600
	citizenrespawninterval = 60
	#一つのコロニーにおける市民の上限数 [初期値: 250, 最低: 4, 最大: 500]
	#Range: 4 ~ 500
	maxcitizenpercolony = 250
	#各ブロック設置後の遅延(大きくすると遅延が長くなる)。 [初期値: 15, 最低: 1, 最大: 500]
	#Range: 1 ~ 500
	builderbuildblockdelay = 15
	#ブロック採掘時の遅延(減少させると遅延が減少します)。 [初期値: 500, 最低: 1, 最大: 10000]
	#Range: 1 ~ 10000
	blockminingdelaymodifier = 500
	#開発者機能を有効にしますか(バグがあるかもしれません)？ [初期値: false]
	enableindevelopmentfeatures = false
	#市民のネームタグを表示しますか？ [初期値: true]
	alwaysrendernametag = true
	#雨の中でも仕事をさせますか？ [初期値: false]
	workersalwaysworkinrain = false
	#コロニーへの入室・退室をプレイヤーに通知しますか？ [初期値: true]
	sendenteringleavingmessages = true
	#プレイヤーが市民の名前を変更することを許可しますか？falseの場合は-1、特定のプレイヤーのみの場合は0、trueの場合は1です。 (どのプレイヤーが名前を変更できるかを設定するには、後述の"特別権限グループ"を参照してください) [初期値: 1, 最低: -1, 最大: 1]
	#Range: -1 ~ 1
	allowglobalnamechanges = 1
	#休日のスペシャルコンテンツを表示しますか？ [初期値: true]
	holidayfeatures = true
	#コンポスト1個分の土の量。 [初期値: 1, 最低: 0, 最大: 100]
	#Range: 0 ~ 100
	dirtfromcompost = 1
	#丸石や石を採掘したときに鉱石が手に入る確率です。（デフォルトで、データパックで他の素材に拡張可能です）これはパーセンテージです。(鉱夫が見つけることができる鉱石を変更するには、「幸運の鉱石のリスト」を参照してください) [初期値: 1, 最低: 0, 最大: 100]
	#Range: 0 ~ 100
	luckyblockchance = 1
	#味方コロニーへのテレポートが有効になる市庁舎の最低レベルです。 [初期値: 3, 最低: 0, 最大: 5]
	#Range: 0 ~ 5
	minthleveltoteleport = 3
	#ビルドツールを使わずに建物を配置しようとした時、ビルドツールの使用を提案します。 [初期値: true]
	suggestbuildtoolplacement = true
	#食品消費量の値です。 [初期値: 1.000000, 最低: 0.100000, 最大: 100.000000]
	#Range: 0.1 ~ 100.0
	foodmodifier = 1.0
	#病気がどれほど一般的か。1 = 一般的、100 = 極稀に。 [初期値: 5, 最低: 1, 最大: 100]
	#Range: 1 ~ 100
	diseasemodifier = 5
	#コロニーの一部がオーナー/オフィサーによってロードされた場合、そのコロニーをロードしたままにするか？(「コロニーのチャンク読み込みの厳密さ」オプションでロードされるチャンクの数を設定します) [初期値: false]
	forceloadcolony = false
	#これは "コロニーを読み込むチャンク数" オプションでロードされるチャンクの数を制御します。この値が高いほど、ロードされるチャンクの数は少なくなります。(一番内側のチャンクが最初にロードされます。) 1 = すべての要求されたチャンクをロードします。 [初期値: 3, 最低: 1, 最大: 15]
	#Range: 1 ~ 15
	colonyloadstrictness = 3
	#あなたが渡した資源を持って逃げ出す邪悪な酒場の訪問者を得るチャンス。単位は%です。 [初期値: 2, 最低: 1, 最大: 100]
	#Range: 1 ~ 100
	badvisitorchance = 2
	#木こりが木の検索の際に確認する、1本の木における最大原木数。 [初期値: 400, 最低: 1, 最大: 1000]
	#Range: 1 ~ 1000
	maxtreesize = 400
	#サプライキャンプの配置制限を無効にする。Skyworldsやそれに類するものを想定している。 [初期値: false]
	nosupplyplacementrestrictions = false
	#この機能を有効にすると、襲撃者が空から出現するようになります。 [初期値: false]
	skyraiders = false

#研究システムに関するすべての設定
[research]
	#クリエイティブモードのプレイヤーに対して、研究を自動的かつ（ほぼ）即座に完了させることを許可します。falseの場合、クリエイティブモードのプレイヤーも研究を始められますが、通常の進行速度になります。 [初期値: true]
	researchcreativecompletion = true
	#ワールドロード時に記録される研究用データパックに関連する情報量を大幅に増やします。 [初期値: false]
	researchdebuglog = false
	#研究を元に戻す際に、プレイヤーに要求される項目の一覧です。 
	researchresetcost = ["minecolonies:ancienttome:1"]

#MineColoniesのコマンドに関する全ての設定
[commands]
	#プレーヤーの /mc rtp コマンドの使用を許可しますか？ [初期値: false]
	canplayerusertpcommand = false
	#プレイヤーの /mc colony teleport コマンドの使用を許可しますか？ [初期値: false]
	canplayerusecolonytpcommand = false
	#同盟コロニーへのテレポートを許可しますか？ [初期値: true]
	canplayeruseallytownhallteleport = true
	#プレイヤーの /mc home コマンドの使用を許可しますか？　※このコマンドはコロニーのオーナーのみが使用できます。 [初期値: false]
	canplayerusehometpcommand = false
	#プレイヤーの /mc colony info コマンドの使用を許可しますか？ [初期値: true]
	canplayeruseshowcolonyinfocommand = true
	#プレイヤーの /mc citizen kill コマンドの使用を許可しますか？ [初期値: false]
	canplayerusekillcitizenscommand = false
	#プレイヤーの /mc colony addOfficer コマンドの使用を許可しますか？ [初期値: true]
	canplayeruseaddofficercommand = true
	#プレイヤーの /mc colony delete コマンドの使用を許可しますか？ [初期値: true]
	canplayerusedeletecolonycommand = true
	#安全な場所へのランダムテレポート検索回数( /mc rtp 使用時) [初期値: 4, 最低: 1, 最大: 10]
	#Range: 1 ~ 10
	numberofattemptsforsafetp = 4

#コロニーのクレームに関するすべての設定
[claims]
	#コロニー領地の最大範囲。これはチャンクで測った半径です。 [初期値: 20, 最低: 1, 最大: 50]
	#Range: 1 ~ 50
	maxColonySize = 20
	#コロニー間の最小距離(チャンク単位) です。 [初期値: 8, 最低: 1, 最大: 200]
	#Range: 1 ~ 200
	minColonyDistance = 8
	#初期コロニー領地の範囲。これはチャンクで測った半径です。 [初期値: 4, 最低: 1, 最大: 15]
	#Range: 1 ~ 15
	initialColonySize = 4
	#コロニーの配置によって初期領地の範囲の最小値/最大値に影響を及ぼすか。 [初期値: false]
	restrictcolonyplacement = false
	#コロニーをワールドへ作成した時の最大領地範囲(ブロック単位)。 [初期値: 8000, 最低: 1000, 最大: 100000]
	#Range: 1000 ~ 100000
	maxdistancefromworldspawn = 8000
	#コロニーをワールドへ作成した時の最小領地範囲(ブロック単位)。 [初期値: 512, 最低: 1, 最大: 1000]
	#Range: 1 ~ 1000
	mindistancefromworldspawn = 512
	#Should officers of a colony receive advancements from that colony? [初期値: true]
	officersreceiveadvancements = true

#MineColoniesの戦闘要素に関する全ての設定項目
[combat]
	#襲撃者を発生させるかどうか。 [初期値: true]
	dobarbariansspawn = true
	#襲撃者の難易度を設定します。 [初期値: 5, 最低: 0, 最大: 10]
	#Range: 0 ~ 10
	barbarianhordedifficulty = 5
	#襲撃者の軍団の最大サイズです。 [初期値: 80, 最低: 6, 最大: 400]
	#Range: 6 ~ 400
	maxBarbarianSize = 80
	#Whether or not raiders can break through obstacles [初期値: true]
	dobarbariansbreakthroughwalls = true
	#レイドが発生する夜の平均日数間隔。 [初期値: 14, 最低: 1, 最大: 50]
	#Range: 1 ~ 50
	averagenumberofnightsbetweenraids = 14
	#レイドが発生する夜の最少日数間隔。 [初期値: 10, 最低: 1, 最大: 30]
	#Range: 1 ~ 30
	minimumnumberofnightsbetweenraids = 10
	#モブが市民を襲うようにするかどうか。 [初期値: true]
	mobattackcitizens = true
	#襲撃者がドアを破壊できるかどうかです。 [初期値: true]
	shouldraiderbreakdoors = true
	#襲われたときに市民はガードに助けを求めるかどうか。 [初期値: true]
	citizencallforhelp = true
	#Attack damage multiplier for Archer Guards. [初期値: 1.000000, 最低: 0.100000, 最大: 5.000000]
	#Range: 0.1 ~ 5.0
	rangerdamagemult = 1.0
	#Attack damage multiplier for Knight Guards. [初期値: 1.000000, 最低: 0.100000, 最大: 5.000000]
	#Range: 0.1 ~ 5.0
	knightdamagemult = 1.0
	#全てのガードの体力倍率を決めます。 [初期値: 1.000000, 最低: 0.100000, 最大: 5.000000]
	#Range: 0.1 ~ 5.0
	guardhealthmult = 1.0
	#MineColoniesのPVPモードをONにします(コロニーを破壊する事ができ、市民は悲嘆にくれるでしょう) [初期値: false]
	pvp_mode = false
	#海賊船が消失するまでの日数です。 [初期値: 3, 最低: 1, 最大: 10]
	#Range: 1 ~ 10
	daysuntilpirateshipsdespawn = 3
	#襲撃者がスポーン可能な最大の Y レベル(高さ)。 [初期値: 200, 最低: 1, 最大: 500]
	#Range: 1 ~ 500
	maxyforbarbarians = 200

#全ての権限設定オプション
[permissions]
	#コロニー保護を有効にしますか？ [初期値: true]
	enablecolonyprotection = true
	#バックアップを保持する最大回数を設定 [初期値: 50, 最低: 3, 最大: 5000]
	#Range: 3 ~ 5000
	maxkeptbackups = 50
	#コロニー保護とは別に、コロニー内での爆発はオフにするべきですか？DAMAGE_NOTHINGは爆発を完全に防ぐことができます。DAMAGE_PLAYERSは、爆発がプレイヤーや敵対モブにダメージを与えることを許可しますが、ブロックや中立・友好モブにはダメージを与えません。DAMAGE_ENTITIESはすべてのエンティティにダメージを与えることができます。DAMAGE_EVERYTHINGは、爆発がエンティティやブロックにダメージを与えることを許可します。 
	#Allowed Values: DAMAGE_NOTHING, DAMAGE_PLAYERS, DAMAGE_ENTITIES, DAMAGE_EVERYTHING
	turnoffexplosionsincolonies = "DAMAGE_ENTITIES"
	#市民の名前を変更するための特別な権限を持っているプレイヤー("名前の変更"参照)。 
	specialpermgroup = ["_Raycoms_"]
	#どのコロニーでもプレイヤーが操作できるブロック(例: 自動販売機) 
	freetointeractblocks = ["dirt", "0 0 0"]
	#許可メッセージの秒数間隔(スパム軽減のため)。 [初期値: 30, 最低: 1, 最大: 1000]
	#Range: 1 ~ 1000
	secondsBetweenPermissionMessages = 30

#MODの互換性に関する全ての設定
[compatibility]
	#市民が図書館で消費するもの 
	configliststudyitems = ["minecraft:paper;400;100", "minecraft:book;600;10"]
	#Items requested by Tavern visitors. 
	configlistrecruitmentitems = ["minecraft:hay_block;3", "minecraft:book;2", "minecraft:enchanted_book;9", "minecraft:diamond;9", "minecraft:emerald;8", "minecraft:baked_potato;1", "minecraft:gold_ingot;2", "minecraft:redstone;2", "minecraft:lapis_lazuli;2", "minecraft:cake;11", "minecraft:sunflower;5", "minecraft:honeycomb;6", "minecraft:quartz;3"]
	#List of ore blocks rarely found magically by Miners (see "Ore Chance"). Includes the block and its chance, separated by exclamation marks. 
	luckyores = ["minecraft:coal_ore!64", "minecraft:copper_ore!48", "minecraft:iron_ore!32", "minecraft:gold_ore!16", "minecraft:redstone_ore!8", "minecraft:lapis_ore!4", "minecraft:diamond_ore!2", "minecraft:emerald_ore!1"]
	#木こりが収穫できる樹木の幹のサイズ：1～8 [初期値: 5, 最低: 1, 最大: 8]
	#Range: 1 ~ 8
	dynamictreeharvestsize = 5
	#Offset for the maximum durability unenchanted rod a T2 Fishing Hut can use, compared to iron tools (250). Thermal Foundation Iron requires +6. T3 huts can use unenchanted rods of any durability level, so long as they can take damage at all. Anything below -250 will only allow vanilla rods, except as allowed by T1. [初期値: 6, 最低: -249, 最大: 250000]
	#Range: -249 ~ 250000
	fishingroddurabilityadjustt2 = 6
	#Offset for the maximum durability unenchanted rod a T1 Fishing Hut can use, compared to other wooden tools (59). Vanilla rods always work, but equivalents would need +6. Default value allows up to Thermal Foundation Silver  Anything below -59 will only allow vanilla rods. [初期値: 22, 最低: -58, 最大: 250000]
	#Range: -58 ~ 250000
	fishingroddurabilityadjustt1 = 22
	#市民が罹りうる全ての病気。名称、珍しさ、治療に必要な全ての成分。 
	diseases = ["Influenza,100,minecraft:carrot,minecraft:potato", "Measles,10,minecraft:dandelion,minecraft:kelp,minecraft:poppy", "Smallpox,1,minecraft:honey_bottle,minecraft:golden_apple"]
	#When loading recipes, generate audit CSV files to help debug datapacks or extra mods. [初期値: false]
	auditcraftingtags = false
	#インベントリデバッグを有効にします。 [初期値: false]
	debuginventories = false

#経路探索に関する全ての設定
[pathfinding]
	#導線のデバッグメッセージの冗長性。 [初期値: 0, 最低: 0, 最大: 10]
	#Range: 0 ~ 10
	pathfindingdebugverbosity = 0
	#市民がレールを利用するための最低連続数。 [初期値: 8, 最低: 5, 最大: 100]
	#Range: 5 ~ 100
	minimumrailstopath = 8
	#導線に使用する追加スレッドの量。 [初期値: 2, 最低: 1, 最大: 10]
	#Range: 1 ~ 10
	pathfindingmaxthreadcount = 2

#要求システムに関する全ての設定
[requestSystem]
	#Should the request system show debug information in the debug.log? Useful if malfunctioning. [初期値: false]
	enabledebuglogging = false
	#リクエストシステムが再試行可能なリクエストに対して実行する最大の試行回数です。これが大きいとサーバーの負荷が高くなります。 [初期値: 3, 最低: 1, 最大: 10]
	#Range: 1 ~ 10
	maximalretries = 3
	#再試行可能なリクエストに対する、リクエストシステムのリトライ間のtick量です。低いとサーバーの負荷が高くなります。 [初期値: 1200, 最低: 30, 最大: 10000]
	#Range: 30 ~ 10000
	delaybetweenretries = 1200
	#Should the request system creatively resolve (if possible) when the player is required to resolve a request? This is a debugging tool and can take a very long time to resolve a request. [初期値: false]
	creativeresolve = false
	#プレイヤーに " /mc colony requestsystem-reset " コマンドの使用を許可しますか？ [初期値: false]
	canplayeruseresetcommand = false

